theme: jekyll-theme-minimal
título : [Nahuel Martinez] 
Descripción : [Desarrollado de sistemas]
logo: /img/WhatsApp Image 2019-05-26 at 12.04.57.jpeg
<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
